import type { PageContentConfig } from './types';

export const DEFAULT_PAGE_CONTENT: PageContentConfig = {
  visibility: {
    heroBadge: true,
    heroTitle: true,
    heroSubtitle: true,
    heroStatsPills: true,
    heroCtaButton: true,
    contactFormCard: true,
    formCategorySelection: true,
    formPhoneField: true,
    formCompanyField: true,
    formSubjectField: true,
    contactInfoCard: true,
    infoHqHeroCard: true,
    infoCoordinatesCard: true,
    infoAddressRow: true,
    infoPhonesRow: true,
    infoEmailRow: true,
    infoWhatsappRow: true,
    infoWorkingHoursRow: true,
    infoRadarMapCard: true,
    faqSection: true,
    footerSection: true,
    footerTagsRow: true,
    footerCoordinatesCol: true,
    footerLinksCol: true,
    footerSocialsRow: true,
  },
  hero: {
    badgeText: "Bureau d'études & Support Écrans LED",
    badgeLocation: "Saint-Ouen (93)",
    titleLine1: "Concrétisez votre projet visuel",
    titleHighlight: "sur-mesure & haute luminosité",
    subtitle: "Du dimensionnement technique à l'installation clé en main, nos ingénieurs LED vous accompagnent pour concevoir l'écran ou le mur d'images parfaitement adapté à votre architecture.",
    stat1Text: "Réponse & devis sous 2h ouvrées",
    stat2Text: "Technologies ColdLED™ & WP Series",
    stat3Text: "Showroom & Ingénierie à Saint-Ouen-sur-Seine",
    ctaButtonText: "Démarrer ma demande de contact",
  },
  form: {
    badge: "Formulaire d'Étude & Contact",
    headerSubtext: "Assistance directe",
    title: "Demandez votre étude personnalisée",
    subtitle: "Remplissez vos critères ci-dessous. Un ingénieur d'affaires PIXIATECH vous contacte sous 2 heures avec pré-chiffrage et conseils d'implantation.",
    step1Title: "1. Choisissez votre type de projet",
    categories: [
      {
        id: 'vitrine-wp',
        title: 'Écran Vitrine Transparent (WP Series)',
        desc: 'Jusqu’à 6 000 nits, transparence optique > 70%',
        tag: 'Haute luminosité',
        visible: true,
      },
      {
        id: 'indoor-finepitch',
        title: 'Mur d’Images Intérieur Ultra-Fine Pitch',
        desc: 'Pitch 0.9mm à 2.5mm, design ultra fin & COB/SMD',
        tag: 'Haute résolution',
        visible: true,
      },
      {
        id: 'outdoor-led',
        title: 'Totem & Écran Géant Extérieur',
        desc: 'Étanchéité IP65, visibilité plein soleil',
        tag: 'Outdoor',
        visible: true,
      },
      {
        id: 'custom-eng',
        title: 'Conception Sur-Mesure & Architecture',
        desc: 'Dalles incurvées, formes libres, intégration DAO',
        tag: 'Sur-mesure',
        visible: true,
      },
    ],
    step2Title: "2. Vos Coordonnées Professionnelles",
    step3Title: "3. Détails & Dimensions de votre projet",
    submitButtonText: "ENVOYER MA DEMANDE DE PROJET",
    trustReassuranceText: "Serveur sécurisé SSL • Aucune cession de données • Réponse garantie",
  },
  info: {
    hqBadge: "Siège Social & Showroom",
    hqLocation: "Île-de-France",
    hqTitle: "PIXIATECH FRANCE",
    hqDesc: "Venez découvrir nos modules d'affichage en conditions réelles dans notre showroom à Saint-Ouen ou échangez en direct avec nos ingénieurs LED.",
    stat1Label: "Délai de traitement",
    stat1Value: "Sous 2h ouvrées",
    stat2Label: "Études & Devis",
    stat2Value: "100% Gratuits",
    coordsTitle: "Nos coordonnées complètes",
    addressLabel: "Adresse Postale",
    addressValue: "5 Rue la fontaine, 93400 Saint-Ouen-sur-Seine",
    phonesLabel: "Lignes Téléphoniques",
    phone1: "+33 7 56 81 66 26",
    phone2: "+33 7 71 59 31 66",
    emailLabel: "Email Officiel",
    emailValue: "contact@pixiatech.com",
    whatsappLabel: "WhatsApp Direct",
    whatsappSubtext: "Discussion instantanée avec un responsable technique",
    whatsappNumber: "+33756816626",
    hoursLabel: "Disponibilité :",
    hoursValue: "Lundi au Vendredi de 09h00 à 18h00 (CET)",
    mapTitle: "Showroom & Ateliers Saint-Ouen",
    mapBadge: "93400 (Métro M13 / M14)",
    mapPinLabel: "PIXIATECH HQ",
  },
  faq: {
    badge: "QUESTIONS FRÉQUENTES & FAQ TECHNIQUE",
    title: "Tout savoir avant de lancer votre projet",
    subtitle: "Retrouvez les réponses aux interrogations les plus fréquentes relatives à nos écrans LED, technologies vitrines et modalités d'installation.",
    items: [
      {
        id: 'faq-1',
        category: 'DEVIS & CHIFFRAGE',
        question: 'Quel est le délai moyen pour obtenir une estimation tarifaire ?',
        answer: 'Notre équipe technique basée à Saint-Ouen-sur-Seine analyse vos cotes et vous fournit un devis détaillé sous 2 heures ouvrées. Pour les architectures complexes sur-mesure nécessitant des calculs de charge ou de dissipation thermique, nous transmettons une étude complète sous 24h à 48h.',
        visible: true,
      },
      {
        id: 'faq-2',
        category: 'VITRINES TRANSPARENTES & COLDLED™',
        question: 'Pourquoi choisir la gamme WP Series & la technologie ColdLED™ ?',
        answer: 'La gamme WP Series combine une luminosité extrême (jusqu\'à 6 000 cd/m²) permettant une visibilité parfaite même en plein soleil, avec une transparence optique supérieure à 70%. La technologie ColdLED™ réduit drastiquement l’échauffement et permet jusqu’à 40% d’économie d’énergie.',
        visible: true,
      },
      {
        id: 'faq-3',
        category: 'INSTALLATION & SUIVI',
        question: 'Assurez-vous l’installation et la mise en service sur site ?',
        answer: 'Oui. Nos techniciens interviennent sur l\'ensemble du territoire français ainsi qu\'en Europe pour la pose des structures, l\'intégration des modules LED, le raccordement électrique et le paramétrage des logiciels de pilotage (Novastar, Colorlight, etc.).',
        visible: true,
      },
      {
        id: 'faq-4',
        category: 'GARANTIE & SAV',
        question: 'Quelles sont les garanties fournies avec les écrans PIXIATECH ?',
        answer: 'Chaque installation bénéficie d’une garantie constructeur de 3 à 5 ans avec lot de maintenance (spare parts) inclus. Notre hotline et notre service après-vente basé en France sont joignables en continu.',
        visible: true,
      }
    ],
  },
  footer: {
    companyName: 'PIXIATECH',
    badgeText: 'ESTIMATION & SHOP',
    description: "Solutions complètes d'affichage dynamique, murs d'images LED ultra haute résolution et dispositifs visuels architecturaux.",
    tags: [
      { id: 'tag-1', text: 'COLDLED™', visible: true },
      { id: 'tag-2', text: 'WP TRANSPARENT', visible: true },
      { id: 'tag-3', text: 'FINE PITCH', visible: true },
      { id: 'tag-4', text: 'FABRICATION & INTÉGRATION', visible: true },
    ],
    col2Title: 'Siège Social & Showroom',
    addressIcon: 'MapPin',
    addressText: '5 Rue la fontaine, 93400 Saint-Ouen-sur-Seine, France',
    phoneIcon: 'Phone',
    phoneText: '+33 7 56 81 66 26 / +33 7 71 59 31 66',
    emailIcon: 'Mail',
    emailText: 'contact@pixiatech.com',
    col3Title: 'Accès & Administration',
    links: [
      {
        id: 'link-1',
        label: 'Boutique en ligne PixiaTech',
        url: 'https://app.pixiatech.com/boutique',
        iconName: 'ShoppingBag',
        visible: true,
      },
      {
        id: 'link-2',
        label: 'Configurateur d’écran LED',
        url: 'https://app.pixiatech.com/?step=1',
        iconName: 'ExternalLink',
        visible: true,
      },
      {
        id: 'link-3',
        label: 'Espace Membre & Console SMTP',
        url: '#smtp-settings',
        iconName: 'Sliders',
        visible: true,
      },
      {
        id: 'link-4',
        label: 'Support & Hotline Technique',
        url: 'tel:+33756816626',
        iconName: 'Headphones',
        visible: true,
      },
    ],
    socialsTitle: 'Réseaux & Échanges Directs',
    socials: [
      {
        id: 'soc-1',
        name: 'LinkedIn',
        url: 'https://www.linkedin.com',
        iconName: 'Linkedin',
        visible: true,
      },
      {
        id: 'soc-2',
        name: 'Instagram',
        url: 'https://www.instagram.com',
        iconName: 'Instagram',
        visible: true,
      },
      {
        id: 'soc-3',
        name: 'WhatsApp',
        url: 'https://wa.me/33756816626',
        iconName: 'MessageSquare',
        visible: true,
      },
      {
        id: 'soc-4',
        name: 'YouTube',
        url: 'https://www.youtube.com',
        iconName: 'Youtube',
        visible: true,
      },
    ],
    copyrightText: '© ' + new Date().getFullYear() + ' PIXIATECH. Tous droits réservés. Spécialiste de l\'affichage dynamique & murs LED.',
    locationBadge: 'Showroom Saint-Ouen (93400)',
    warrantyText: 'Garantie constructeur 3 à 5 ans',
  },
};